

-- VISUALIZAR TABELA
SELECT * FROM TABELA_NOVA;
/*
-- ISERIR NOVAS LINHAS 
INSERT INTO TABELA_NOVA VALUES ('TÁ DANDO CERTO, EU ACHO','86996545321','FFF@GMAIL.COM'),('TÁ DANDO CERTO','86996544422','EEE@GMAIL.COM');


--DELETAR LINHAS 
DELETE FROM TABELA_NOVA WHERE ID_TABELA IN (8,9,10,11);

-- ISERIR NOVAS LINHAS 
INSERT INTO TABELA_NOVA VALUES ('DEU CERTO','86996544022','FDSA@GMAIL.COM'),('TÁ DANDO CERTO','86996544422','EEE@GMAIL.COM');

-- MUDAR DADO DE UMA COLUNA
UPDATE TABELA_NOVA SET EMAIL='ATUALIZADO@GMAIL.COM' WHERE ID_TABELA = 1;*/

--UPDATE TABELA_NOVA SET EMAIL='DOIDO@GMAIL.COM' WHERE ID_TABELA IN (4);